version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 570865379429.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo "Building the Maven project..."
      - mvn clean package
      - cp target/livedemo.war .
      - echo Building the Docker image...
      - docker build -t sampleecrrepo .
      - docker tag sampleecrrepo:latest 570865379429.dkr.ecr.ap-south-1.amazonaws.com/sampleecrrepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 570865379429.dkr.ecr.ap-south-1.amazonaws.com/sampleecrrepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"code-pipeline-ecr","imageUri":"%s"}]'570865379429.dkr.ecr.ap-south-1.amazonaws.com/sampleecrrepo:latest  > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
