version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w4m8p1h4
  build:
    commands:
      - echo Build started on `date`
      - echo "Building the Maven project..."
      - mvn clean package
      - cp target/livedemo.war .
      - echo Building the Docker image...
      - docker build -t testrepository .
      - docker tag demobased1234dockerecrrepopublic1:latest public.ecr.aws/w4m8p1h4/demobased1234dockerecrrepopublic1:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/w4m8p1h4/demobased1234dockerecrrepopublic1:latest
      - echo Writing image definitions file...
      - printf '[{"name":"code-pipeline-ecr","imageUri":"%s"}]'public.ecr.aws/w4m8p1h4/demobased1234dockerecrrepopublic1:latest  > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
